### ISSUE TITLE
Speed up IIC calc with Rcpp

### ISSUE THREAD

**Issue by BBranoff** [FMestre1/lconnect#3]
Not really a bug, as the package works, but I did find it very slow when calculating the IIC metric over large areas with 1000+ patches. After some time, I realized the nested for loops in filling the "out" matrix was the primary bottleneck (from the 'con_metric' function). As this is a known weakness in R, and as many have gone around it by outsourcing to C++ via the Rcpp package, I thought I would do the same. Below is an Rcpp version of the IIC matrix filling routine. This function works much much faster than the R version. I don't have a benchmark but its a least an order of magnitude faster, maybe two. To be clear, this would replace lines 189-196 of the 'con_metric' function on the GitHub page. I'm not super familiar with C++ so I'm sure there are some syntax issues, but the indexing of the vectors and matrices seems to be correct and this provides the same results as the original R version. 

```
##  the original R code to setup the final 'out' matrix
 out <- matrix(NA, nrow = length(area_c), ncol = length(area_c))
 out <-IICRcpp(out[1,],area_c,as.numeric(row.names(short_p))-1,short_p)
## the new nested loop routine to replace lines 189-196
cppFunction(
  "NumericMatrix IICRcpp(NumericVector x,NumericVector area_c, NumericVector names,NumericMatrix short_p) {
   const int nr = x.length();
   const int nv = names.length();
   NumericMatrix y(nr, nr);
    for (int i=0; i < nv;i++) {
      for (int j=0; j < nv; j++) {
        y(names(i),names(j)) =(area_c(names(i)) * area_c(names(j)))/(1 + short_p(i, j));
      }
    }
   return y;
}")
```

**Comment by bmsasilva** [comment]
Hi,
first let me thank you for your interest in our package and in the detailed description you provide in how to improve it. We are not very familiar with C but we will try to incorporate your code in a revised version (along with other changes we are already working on). In that case we would include you as a contributor if that's ok by you.
Regards

**Comment by BBranoff** [comment]
Im happy to be included but its really not necessary. Im not sure how easy
it is to incorporate rcpp into a package as I imagine it requires special
compilation.

In any case, Ive also written a separate function to drop the memory
requirement of the following portion:

d1 <- upper.tri(as.matrix(distance)) * as.matrix(distance)
    d1[d1 == 0] <- NA
    e1 <- as.data.frame(which(d1 < max_dist, arr.ind = TRUE, useNames =
FALSE))

I found this would require too much memory if the number of patches was
above 10,000. Again C++ alleviates these memory issues. Id be happy to
include another "issue" if you like and if you think these Rcpp functions
can be incorporated into the new updates.

Thank you for developing this software, it has been critical for my work.

**Comment by bmsasilva** [comment]
Hi,
after some struggle with Rcpp we finally managed to incorporate it and your C++ function in the package. 
I'm going to close this issue but feel free to open a new one for that memory issue you found.
Thanks again for this improvement.
