### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by neiloliveira** [FMestre1/lconnect#7]
I have been trying to calculate IIC using patch_imp function, but I keep getting this error message:

__Error in dconn[i] <- 100 * ((full_conn - partial_conn)/full_conn) : 
  replacement has length zero
In addition: Warning message:
In max(clusters) : no non-missing arguments to max; returning -Inf__

Also, after I Import and convert a shapefile to an object of class "lconnect", If I try to plot the shp, I get this message:

_**Error in plot_sf(x, ...) : 
  NA value(s) in bounding box. Trying to plot empty geometries?**_
  

I have tried to correct the geometry of the shp, I have converted multipolygon to poligon, I have created new shapes and nothing seems to work. 

I'd appreciate any help with this issue. 

Thanks in advance.

**Comment by FMestre1** [comment]
Hello,
Can you send de data em code, replicating your error?
Thanks,
Frederico

**Comment by neiloliveira** [comment]
Hello, 

After so many trials, I got it right. 
I was first trying with a shapefile with more than one class of vegetation patches (Primary and Secondary). When I joined the classes into  a single one, the analysis ran smoothly (although it took a while to complete). 

Thanks for answering. 

Neil

**Comment by FMestre1** [comment]
I'm glad it worked out!
Frederico
